# Nombre de la aplicación
spring.application.name=WhatCanICook

# ===== DATASOURCE (MySQL en Docker) =====
spring.datasource.url=jdbc:mysql://localhost:3309/WhatCanICook?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# (opcional pero recomendado)
spring.jpa.open-in-view=false