# Nombre de la aplicaci\uFFFDn
spring.application.name=WhatCanICook

# ===== DATASOURCE (MySQL en Docker) =====
spring.datasource.url=jdbc:mysql://localhost:3309/WhatCanICook?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
    # update -> crea tablas que no existen y a\u00F1ade columnas nuevas
    # update -> no borra columnas, ni tablas
    # update -> no maneja bien cambios complejos
# spring.jpa.hibernate.ddl-auto=none
    # none -> no hace nada.
    # none -> Asume que la db est\u00E1 creada y correcta
# spring.jpa.hibernate.ddl-auto=validate
    # validate -> comprueba que las tablas existen
    # validate -> comprueba que las columnas coinciden
# spring.jpa.hibernate.ddl-auto=create
    # create -> borra el esquema
    # create -> crea todo desde cero
    # pierde todos los datos en cada arranque
# spring.jpa.hibernate.ddl-auto=create-drop
    # create-drop -> crea el esquema al arrancar
    # create-drop -> lo borra al apagar la app
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# (opcional pero recomendado)
spring.jpa.open-in-view=false